defaults:
  - eval: cognitive_map
  - landmark_spec: all_landmarks
  - _self_

device: "cpu"
mode: eval
eval_type: 'CognitiveMapping'
environment: 'gv_four_rooms.9x9_eval.yaml'
seed: 1

# model saving
model:
  policy_type: "RecurrentPPO"
  name_prefix: 'ppo_model_9x9'
  save_freq: 10_000
  total_timesteps: 2_000_000
  n_steps: 2048

wandb:
  mode: 'disabled'



